name: Deploy Theme to Cloudways

on:
  push:
    branches: [ content-blocks ]
    paths:
      - 'themes/abf-styleguide/**'
  workflow_dispatch: # Manueller Trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Deploy to Cloudways
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.CLOUDWAYS_HOST }}
        username: ${{ secrets.CLOUDWAYS_USERNAME }}
        key: ${{ secrets.CLOUDWAYS_SSH_KEY }}
        port: ${{ secrets.CLOUDWAYS_PORT }}
        script: |
          # Ins wp-content Verzeichnis wechseln
          cd /home/master/applications/${{ secrets.CLOUDWAYS_APP_ID }}/public_html/wp-content
          
          # Git Repository aktualisieren
          git fetch origin
          git reset --hard origin/content-blocks
          
          # Berechtigungen setzen
          chown -R master:master themes/abf-styleguide
          find themes/abf-styleguide -type d -exec chmod 755 {} \;
          find themes/abf-styleguide -type f -exec chmod 644 {} \;
          
          echo "✅ Theme erfolgreich deployed!"
    
    - name: Deployment Status
      run: echo "🚀 Theme wurde auf Cloudways deployed!" 