<?php
/**
 * ACF Fields for Hero Block
 */

// Get color choices from the main function
$color_choices = function_exists('abf_get_color_choices') ? abf_get_color_choices() : array();

return array(
    'key' => 'group_hero_block',
    'title' => 'Hero Block Felder',
    'fields' => array(
        // Background Settings
        array(
            'key' => 'field_hero_background_type',
            'label' => 'Hintergrund Typ',
            'name' => 'hero_background_type',
            'type' => 'select',
            'instructions' => 'Wähle zwischen Bild oder Video',
            'required' => 1,
            'choices' => array(
                'image' => 'Bild',
                'video' => 'Video',
            ),
            'default_value' => 'image',
            'wrapper' => array('width' => '100'),
        ),
        array(
            'key' => 'field_hero_background_image',
            'label' => 'Hintergrund Bild',
            'name' => 'hero_background_image',
            'type' => 'image',
            'instructions' => 'Wähle ein Hintergrund-Bild (wird als "cover" dargestellt)',
            'required' => 0,
            'return_format' => 'array',
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_hero_background_type',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_hero_background_video',
            'label' => 'Hintergrund Video',
            'name' => 'hero_background_video',
            'type' => 'file',
            'instructions' => 'Wähle ein Hintergrund-Video (MP4 empfohlen, läuft automatisch in Schleife)',
            'required' => 0,
            'return_format' => 'array',
            'mime_types' => 'mp4,webm,ogg',
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_hero_background_type',
                        'operator' => '==',
                        'value' => 'video',
                    ),
                ),
            ),
        ),
        
        // Headline Settings
        array(
            'key' => 'field_hero_headline',
            'label' => 'Headline',
            'name' => 'hero_headline',
            'type' => 'textarea',
            'instructions' => 'Gib hier die Hauptüberschrift ein',
            'required' => 1,
            'rows' => 3,
        ),
        array(
            'key' => 'field_hero_headline_tag',
            'label' => 'Headline HTML Tag',
            'name' => 'hero_headline_tag',
            'type' => 'select',
            'instructions' => 'Wähle das HTML-Tag für die Headline',
            'required' => 1,
            'choices' => array(
                'h1' => 'H1',
                'h2' => 'H2',
                'h3' => 'H3',
                'h4' => 'H4',
                'h5' => 'H5',
                'h6' => 'H6',
            ),
            'default_value' => 'h1',
            'wrapper' => array('width' => '25'),
        ),
        array(
            'key' => 'field_hero_headline_weight',
            'label' => 'Headline Schriftgewicht',
            'name' => 'hero_headline_weight',
            'type' => 'select',
            'instructions' => 'Wähle das Schriftgewicht aus den Theme-Einstellungen',
            'required' => 1,
            'choices' => function_exists('abf_get_typography_font_weights') ? abf_get_typography_font_weights() : array(
                '300' => 'Light (300)',
                '400' => 'Regular (400)',
                '500' => 'Medium (500)',
                '600' => 'Semi-Bold (600)',
                '700' => 'Bold (700)',
            ),
            'default_value' => '700',
            'wrapper' => array('width' => '25'),
        ),
        array(
            'key' => 'field_hero_headline_size',
            'label' => 'Headline Schriftgröße',
            'name' => 'hero_headline_size',
            'type' => 'select',
            'instructions' => 'Wähle die Schriftgröße aus den Theme-Einstellungen',
            'required' => 1,
            'choices' => function_exists('abf_get_typography_font_sizes') ? abf_get_typography_font_sizes() : array(
                '12' => '12px (Small)',
                '18' => '18px (Body)', 
                '24' => '24px (H2)',
                '36' => '36px (H1)',
                '48' => '48px (XL)',
                '60' => '60px (XXL)',
                '72' => '72px (3XL)',
            ),
            'default_value' => '48',
            'wrapper' => array('width' => '25'),
        ),
        array(
            'key' => 'field_hero_headline_color',
            'label' => 'Headline Farbe',
            'name' => 'hero_headline_color',
            'type' => 'select',
            'instructions' => 'Wähle eine Farbe für die Headline',
            'required' => 1,
            'choices' => $color_choices,
            'default_value' => 'primary',
            'wrapper' => array('width' => '25'),
        ),
        
        // Subline Settings
        array(
            'key' => 'field_hero_subline',
            'label' => 'Subline',
            'name' => 'hero_subline',
            'type' => 'textarea',
            'instructions' => 'Gib hier die Unterüberschrift ein (optional)',
            'required' => 0,
            'rows' => 2,
        ),
        array(
            'key' => 'field_hero_subline_tag',
            'label' => 'Subline HTML Tag',
            'name' => 'hero_subline_tag',
            'type' => 'select',
            'instructions' => 'Wähle das HTML-Tag für die Subline',
            'required' => 1,
            'choices' => array(
                'h1' => 'H1',
                'h2' => 'H2',
                'h3' => 'H3',
                'h4' => 'H4',
                'h5' => 'H5',
                'h6' => 'H6',
                'p' => 'Paragraph',
            ),
            'default_value' => 'h2',
            'wrapper' => array('width' => '25'),
        ),
        array(
            'key' => 'field_hero_subline_weight',
            'label' => 'Subline Schriftgewicht',
            'name' => 'hero_subline_weight',
            'type' => 'select',
            'instructions' => 'Wähle das Schriftgewicht aus den Theme-Einstellungen',
            'required' => 1,
            'choices' => function_exists('abf_get_typography_font_weights') ? abf_get_typography_font_weights() : array(
                '300' => 'Light (300)',
                '400' => 'Regular (400)',
                '500' => 'Medium (500)',
                '600' => 'Semi-Bold (600)',
                '700' => 'Bold (700)',
            ),
            'default_value' => '400',
            'wrapper' => array('width' => '25'),
        ),
        array(
            'key' => 'field_hero_subline_size',
            'label' => 'Subline Schriftgröße',
            'name' => 'hero_subline_size',
            'type' => 'select',
            'instructions' => 'Wähle die Schriftgröße aus den Theme-Einstellungen',
            'required' => 1,
            'choices' => function_exists('abf_get_typography_font_sizes') ? abf_get_typography_font_sizes() : array(
                '12' => '12px (Small)',
                '18' => '18px (Body)', 
                '24' => '24px (H2)',
                '36' => '36px (H1)',
                '48' => '48px (XL)',
                '60' => '60px (XXL)',
                '72' => '72px (3XL)',
            ),
            'default_value' => '24',
            'wrapper' => array('width' => '25'),
        ),
        array(
            'key' => 'field_hero_subline_color',
            'label' => 'Subline Farbe',
            'name' => 'hero_subline_color',
            'type' => 'select',
            'instructions' => 'Wähle eine Farbe für die Subline',
            'required' => 1,
            'choices' => $color_choices,
            'default_value' => 'secondary',
            'wrapper' => array('width' => '25'),
        ),
        
        // Button Settings
        array(
            'key' => 'field_hero_button_text',
            'label' => 'Button Text',
            'name' => 'hero_button_text',
            'type' => 'text',
            'instructions' => 'Gib hier den Button-Text ein (optional)',
            'required' => 0,
        ),
        array(
            'key' => 'field_hero_button_url',
            'label' => 'Button Link',
            'name' => 'hero_button_url',
            'type' => 'link',
            'instructions' => 'Wähle ein Linkziel aus Seiten, Beiträgen oder externe URL. "#" für Anker-Links ist erlaubt.',
            'return_format' => 'array',
            'required' => 0,
        ),
        array(
            'key' => 'field_hero_button_bg_color',
            'label' => 'Button Hintergrundfarbe',
            'name' => 'hero_button_bg_color',
            'type' => 'select',
            'instructions' => 'Wähle die Hintergrundfarbe des Buttons',
            'required' => 1,
            'choices' => array_merge(array('white' => 'Weiß'), $color_choices),
            'default_value' => 'primary',
            'wrapper' => array('width' => '25'),
        ),
        array(
            'key' => 'field_hero_button_text_color',
            'label' => 'Button Textfarbe',
            'name' => 'hero_button_text_color',
            'type' => 'select',
            'instructions' => 'Wähle die Textfarbe des Buttons',
            'required' => 1,
            'choices' => array_merge(array('white' => 'Weiß'), $color_choices),
            'default_value' => 'white',
            'wrapper' => array('width' => '25'),
        ),
        array(
            'key' => 'field_hero_button_hover_bg',
            'label' => 'Button Hover Hintergrund',
            'name' => 'hero_button_hover_bg',
            'type' => 'select',
            'instructions' => 'Wähle die Hintergrundfarbe beim Hover',
            'required' => 1,
            'choices' => array_merge(array('white' => 'Weiß'), $color_choices),
            'default_value' => 'secondary',
            'wrapper' => array('width' => '25'),
        ),
        array(
            'key' => 'field_hero_button_hover_text',
            'label' => 'Button Hover Textfarbe',
            'name' => 'hero_button_hover_text',
            'type' => 'select',
            'instructions' => 'Wähle die Textfarbe beim Hover',
            'required' => 1,
            'choices' => array_merge(array('white' => 'Weiß'), $color_choices),
            'default_value' => 'white',
            'wrapper' => array('width' => '25'),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/hero',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Felder für den Hero-Block',
); 